rooms:
  - id:  # 需要上传的直播间 ID，长号短号均可
    tags:  # 上传所需的tag，英文逗号分割
    channel:  # 上传所需的频道，空格分割
    title:  # 视频标题，可以使用模版
    description:  # 视频描述，可以使用模版
    dynamic:  # 动态简介，可以使用模版
    conditions:  # 额外的tag条件，注意判断逻辑为&
    - item:  # 字段，例如title
      regexp:  # 匹配的正则
      tags:  # 该条件下额外的tag
      channel:  # 该条件下额外的频道
      process:  # 当匹配到对应条件时是否处理，默认为true
